package model.common.serviceinterface;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import model.common.DeptViewSDO;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 17 15:12:02 PST 2011
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="/model/common/", name="C2AMService",
    wsdlLocation="model/common/serviceinterface/C2AMService.wsdl")
@SDODatabinding(schemaLocation="model/common/serviceinterface/C2AMService.xsd")
public interface C2AMService {
    public static final String NAME = "{/model/common/}C2AMService";

    @WebMethod(action="/model/common/getDeptView1", operationName="getDeptView1")
    @RequestWrapper(targetNamespace="/model/common/types/", localName="getDeptView1")
    @ResponseWrapper(targetNamespace="/model/common/types/", localName="getDeptView1Response")
    @WebResult(name="result")
    DeptViewSDO getDeptView1(@WebParam(mode = WebParam.Mode.IN, name="deptno")
        Integer deptno) throws ServiceException;

    @WebMethod(action="/model/common/createDeptView1", operationName="createDeptView1")
    @RequestWrapper(targetNamespace="/model/common/types/", localName="createDeptView1")
    @ResponseWrapper(targetNamespace="/model/common/types/", localName="createDeptView1Response")
    @WebResult(name="result")
    DeptViewSDO createDeptView1(@WebParam(mode = WebParam.Mode.IN, name="deptView1")
        DeptViewSDO deptView1) throws ServiceException;

    @WebMethod(action="/model/common/updateDeptView1", operationName="updateDeptView1")
    @RequestWrapper(targetNamespace="/model/common/types/", localName="updateDeptView1")
    @ResponseWrapper(targetNamespace="/model/common/types/", localName="updateDeptView1Response")
    @WebResult(name="result")
    DeptViewSDO updateDeptView1(@WebParam(mode = WebParam.Mode.IN, name="deptView1")
        DeptViewSDO deptView1) throws ServiceException;

    @WebMethod(action="/model/common/deleteDeptView1", operationName="deleteDeptView1")
    @RequestWrapper(targetNamespace="/model/common/types/", localName="deleteDeptView1")
    @ResponseWrapper(targetNamespace="/model/common/types/", localName="deleteDeptView1Response")
    void deleteDeptView1(@WebParam(mode = WebParam.Mode.IN, name="deptView1")
        DeptViewSDO deptView1) throws ServiceException;

    @WebMethod(action="/model/common/mergeDeptView1", operationName="mergeDeptView1")
    @RequestWrapper(targetNamespace="/model/common/types/", localName="mergeDeptView1")
    @ResponseWrapper(targetNamespace="/model/common/types/", localName="mergeDeptView1Response")
    @WebResult(name="result")
    DeptViewSDO mergeDeptView1(@WebParam(mode = WebParam.Mode.IN, name="deptView1")
        DeptViewSDO deptView1) throws ServiceException;

    @WebMethod(action="/model/common/findDeptView1", operationName="findDeptView1")
    @RequestWrapper(targetNamespace="/model/common/types/", localName="findDeptView1")
    @ResponseWrapper(targetNamespace="/model/common/types/", localName="findDeptView1Response")
    @WebResult(name="result")
    List<DeptViewSDO> findDeptView1(@WebParam(mode = WebParam.Mode.IN, name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;
}
